hbase:
  config:
    hbase.zookeeper.quorum: 10.10.254.131:31336
    hbase.zookeeper.port: 31336
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000
  phoenix:
    datasource:
      url: 10.10.254.131:31336
      driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug