hbase:
  config:
    hbase.zookeeper.quorum: 192.168.100.201,192.168.100.202,192.168.100.203
    hbase.zookeeper.port: 2181
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000
  phoenix:
    datasource.url: 192.168.100.201:2181
    datasource.driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug